In [235]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [236]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],
                [4,5,6],
                 [7,8,9]],

                 [[10,11,12],
                 [13,14,15],
                 [16,17,18]]
                ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [237]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [238]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((3, 3), 2, dtype('int64'), 9, numpy.ndarray)

In [239]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [240]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [241]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [242]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [243]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [244]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, size = (7,2))

array([[9, 1],
       [9, 3],
       [7, 6],
       [8, 7],
       [4, 1],
       [4, 7],
       [9, 8]], dtype=int32)

In [245]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.28093451, 0.54269608, 0.14092422, 0.80219698, 0.07455064],
       [0.98688694, 0.77224477, 0.19871568, 0.00552212, 0.81546143],
       [0.70685734, 0.72900717, 0.77127035, 0.07404465, 0.35846573]])

In [246]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size = (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

---> Well, we don't have anything really random, we have pseudo random stuff
we have fixed numbers, just at different seeds
but at one seed, the numbers remain same

In [247]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 10, size=(3, 7))
print(random_array.shape)
# Find the unique numbers in the array you just created
np.unique(random_array)

(3, 7)


array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [248]:
# Find the 0'th index of the latest array you created
random_array[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [249]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [250]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [251]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a1 = np.random.randint(0, 10, size = (3,5))
ones = np.ones((3,5))


In [252]:
a1

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]], dtype=int32)

In [253]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [254]:
# Add the two arrays together
a1 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [255]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [256]:
# Try add the array of ones and the other most recent array together
ones + a1

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

---> Broadcasting only works when:

Dimensions are equal or

One of the dimensions is 1 (so it can stretch)

Here, none of those rules are satisfied -> broadcasting fails

The fix would be to just take the transpose of one array and adding to the other one

In [257]:
a1 + ones.T

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [258]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [259]:
# Subtract the new array of ones from the other most recent array
a1 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [260]:
# Multiply the ones array with the latest array
ones * a1

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [261]:
# Take the latest array to the power of 2 using '**'
a1 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [262]:
# Do the same thing with np.square()
np.square(a1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [263]:
# Find the mean of the latest array using np.mean()
np.mean(a1)

np.float64(3.8666666666666667)

In [264]:
# Find the maximum of the latest array using np.max()
np.max(a1)

np.int32(9)

In [265]:
# Find the minimum of the latest array using np.min()
np.min(a1)

np.int32(0)

In [266]:
# Find the standard deviation of the latest array
np.std(a1)

np.float64(2.578543947441829)

In [267]:
# Find the variance of the latest array
np.var(a1)

np.float64(6.648888888888889)

In [268]:
# Reshape the latest array to (3, 5, 1)
a1.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]], dtype=int32)

In [271]:
# Transpose the latest array
a1.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]], dtype=int32)

What does the transpose do?

-->Transpose flips the shape of the array

In [272]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(0, 10, size = (3,3) )
mat2 = np.random.randint(0, 10, size = (3,2))

In [276]:
# Perform a dot product on the two newest arrays you created
mat1.dot(mat2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]], dtype=int32)

In [278]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(0, 10, size = (4,3))
mat4 = np.random.randint(0, 10, size = (4,3))

In [279]:
# Perform a dot product on the two newest arrays you created
mat3.dot(mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

---> It doesn't work because of the shapes
     It should be like (4,3) and (3,4) {inner ones should be equal}
     Therefore, we can just take transpose of one and then do the dot product

In [280]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
mat3.dot(mat4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [281]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random1 = np.random.randint(0, 10, size=(4, 2))
random2 = np.random.randint(0, 10, size=(4, 2))

In [282]:
random1

array([[6, 6],
       [7, 4],
       [2, 7],
       [5, 2]], dtype=int32)

In [283]:
random2

array([[0, 2],
       [4, 2],
       [0, 4],
       [9, 6]], dtype=int32)

In [285]:
# Compare the two arrays with '>'
random1 > random2

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [ ]:
What happens when you compare the arrays with `>`?

--->Each element of each array gets compared with each other

In [286]:
# Compare the two arrays with '>='
random1 >= random2

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [287]:
# Find which elements of the first array are greater than 7
random1 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [288]:
# Which parts of each array are equal? (try using '==')
random1 == random2

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [289]:
# Sort one of the arrays you just created in ascending order
np.sort(random1)

array([[6, 6],
       [4, 7],
       [2, 7],
       [2, 5]], dtype=int32)

In [290]:
# Sort the indexes of one of the arrays you just created
np.argsort(random1)

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0]])

In [291]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random1)

np.int64(2)

In [292]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random1)

np.int64(4)

In [293]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random1, axis = 1)

array([0, 0, 1, 0])

In [294]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random1, axis = 0)

array([2, 3])

In [295]:
# Create an array of normally distributed random numbers
np.random.randn(3,3)

array([[-0.03582604,  1.56464366, -2.6197451 ],
       [ 0.8219025 ,  0.08704707, -0.29900735],
       [ 0.09176078, -1.98756891, -0.21967189]])

In [296]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.